# Generated by Django 2.0.1 on 2019-10-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='environment_id',
        ),
    ]
